apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://172.22.0.30:8086
    jsonData:
      version: Flux
      organization: iot-cyberrange
      defaultBucket: sensors
    secureJsonData:
      token: secure-admin-token-abc123xyz987
    isDefault: true
